mod activities;
mod app_role_assignments;
mod authentication;
mod calendar_groups;
mod calendar_view;
mod calendars;
mod channels;
mod child_folders;
mod contact_folders;
mod contacts;
mod created_objects;
mod default_calendar;
mod device_management_troubleshooting_events;
mod direct_reports;
mod events;
mod events_instances;
mod extensions;
mod followed_sites;
mod inference_classification;
mod insights;
mod joined_teams;
mod license_details;
mod mail_folders;
mod mailbox_settings;
mod managed_app_registrations;
mod managed_devices;
mod member_of;
mod onenote;
mod onenote_notebooks;
mod onenote_pages;
mod onenote_section_groups;
mod onenote_sections;
mod online_meetings;
mod outlook;
mod owned_devices;
mod owned_objects;
mod photos;
mod presence;
mod registered_devices;
mod request;
mod scoped_role_member_of;
mod settings;
mod teamwork;
mod todo;
mod todo_lists;
mod todo_lists_tasks;
mod transitive_member_of;
mod users_attachments;
mod users_messages;

pub use activities::*;
pub use app_role_assignments::*;
pub use authentication::*;
pub use calendar_groups::*;
pub use calendar_view::*;
pub use calendars::*;
pub use channels::*;
pub use child_folders::*;
pub use contact_folders::*;
pub use contacts::*;
pub use created_objects::*;
pub use default_calendar::*;
pub use device_management_troubleshooting_events::*;
pub use direct_reports::*;
pub use events::*;
pub use events_instances::*;
pub use extensions::*;
pub use followed_sites::*;
pub use inference_classification::*;
pub use insights::*;
pub use joined_teams::*;
pub use license_details::*;
pub use mail_folders::*;
pub use mailbox_settings::*;
pub use managed_app_registrations::*;
pub use managed_devices::*;
pub use member_of::*;
pub use onenote::*;
pub use onenote_notebooks::*;
pub use onenote_pages::*;
pub use onenote_section_groups::*;
pub use onenote_sections::*;
pub use online_meetings::*;
pub use outlook::*;
pub use owned_devices::*;
pub use owned_objects::*;
pub use photos::*;
pub use presence::*;
pub use registered_devices::*;
pub use request::*;
pub use scoped_role_member_of::*;
pub use settings::*;
pub use teamwork::*;
pub use todo::*;
pub use todo_lists::*;
pub use todo_lists_tasks::*;
pub use transitive_member_of::*;
pub use users_attachments::*;
pub use users_messages::*;
