name: Cargo Clippy

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  clippy_check:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Run Clippy
        run: cargo clippy --all-targets --all-features --workspace
